"""initial schema

Revision ID: d42564d3dad6
Revises:
Create Date: 2026-09-13 20:46:40.360630
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d42564d3dad6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("default_language", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agency_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("phone_e164", sa.String(length=24), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("preferred_language", sa.String(length=16), nullable=False),
        sa.Column("contact_consent_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_agency_id"), "leads", ["agency_id"], unique=False)
    op.create_table(
        "properties",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agency_id", sa.String(length=36), nullable=False),
        sa.Column("external_ref", sa.String(length=40), nullable=False),
        sa.Column(
            "transaction_type", sa.Enum("sale", "rent", name="transactiontype"), nullable=False
        ),
        sa.Column("property_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("address_display", sa.String(length=180), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("postal_code", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("bedrooms", sa.Integer(), nullable=False),
        sa.Column("bathrooms", sa.Integer(), nullable=False),
        sa.Column("area_m2", sa.Integer(), nullable=False),
        sa.Column("amenities", sa.Text(), nullable=False),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_ref"),
    )
    op.create_index(op.f("ix_properties_agency_id"), "properties", ["agency_id"], unique=False)
    op.create_index(op.f("ix_properties_city"), "properties", ["city"], unique=False)
    op.create_table(
        "viewing_slots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Enum("available", "booked", name="slotstatus"), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_viewing_slots_property_id"), "viewing_slots", ["property_id"], unique=False
    )
    op.create_table(
        "viewings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slot_id", sa.String(length=36), nullable=False),
        sa.Column("lead_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("confirmation_channel", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["viewing_slots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_viewings_idempotency_key"),
        sa.UniqueConstraint("slot_id", name="uq_viewings_slot_id"),
    )
    op.create_index(op.f("ix_viewings_lead_id"), "viewings", ["lead_id"], unique=False)
    op.create_index(op.f("ix_viewings_slot_id"), "viewings", ["slot_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_viewings_slot_id"), table_name="viewings")
    op.drop_index(op.f("ix_viewings_lead_id"), table_name="viewings")
    op.drop_table("viewings")
    op.drop_index(op.f("ix_viewing_slots_property_id"), table_name="viewing_slots")
    op.drop_table("viewing_slots")
    op.drop_index(op.f("ix_properties_city"), table_name="properties")
    op.drop_index(op.f("ix_properties_agency_id"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_leads_agency_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_table("agencies")
    # ### end Alembic commands ###
