"""browser mvp call records

Revision ID: ed11587940a9
Revises: d42564d3dad6
Create Date: 2026-09-14 12:25:44.522360
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ed11587940a9"
down_revision: str | None = "d42564d3dad6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead_preferences",
        sa.Column("lead_id", sa.String(length=36), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=True),
        sa.Column(
            "transaction_type", sa.Enum("sale", "rent", name="transactiontype"), nullable=True
        ),
        sa.Column("budget_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("bedrooms_min", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("lead_id"),
    )
    op.create_table(
        "calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("agency_id", sa.String(length=36), nullable=False),
        sa.Column("lead_id", sa.String(length=36), nullable=False),
        sa.Column("booking_id", sa.String(length=36), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("disposition", sa.String(length=40), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["viewings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id"),
    )
    op.create_index(op.f("ix_calls_agency_id"), "calls", ["agency_id"], unique=False)
    op.create_index(op.f("ix_calls_lead_id"), "calls", ["lead_id"], unique=False)
    op.create_index(op.f("ix_calls_session_id"), "calls", ["session_id"], unique=True)
    op.create_index(op.f("ix_calls_status"), "calls", ["status"], unique=False)
    op.create_table(
        "call_turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("call_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("interrupted", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id", "sequence", name="uq_call_turn_sequence"),
    )
    op.create_index(op.f("ix_call_turns_call_id"), "call_turns", ["call_id"], unique=False)
    op.create_table(
        "property_matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("call_id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("presented_to_caller", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id", "property_id", name="uq_property_match_call_property"),
    )
    op.create_index(
        op.f("ix_property_matches_call_id"), "property_matches", ["call_id"], unique=False
    )
    op.create_index(
        op.f("ix_property_matches_property_id"), "property_matches", ["property_id"], unique=False
    )
    op.create_table(
        "tool_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("call_id", sa.String(length=36), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("arguments_redacted", sa.Text(), nullable=False),
        sa.Column("result_redacted", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_executions_call_id"), "tool_executions", ["call_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_executions_call_id"), table_name="tool_executions")
    op.drop_table("tool_executions")
    op.drop_index(op.f("ix_property_matches_property_id"), table_name="property_matches")
    op.drop_index(op.f("ix_property_matches_call_id"), table_name="property_matches")
    op.drop_table("property_matches")
    op.drop_index(op.f("ix_call_turns_call_id"), table_name="call_turns")
    op.drop_table("call_turns")
    op.drop_index(op.f("ix_calls_status"), table_name="calls")
    op.drop_index(op.f("ix_calls_session_id"), table_name="calls")
    op.drop_index(op.f("ix_calls_lead_id"), table_name="calls")
    op.drop_index(op.f("ix_calls_agency_id"), table_name="calls")
    op.drop_table("calls")
    op.drop_table("lead_preferences")
    # ### end Alembic commands ###
